meta_product_name: "Ghislain Chavanne"
meta_title: "Ghislain Chavanne - Développeur Full-Stack"
meta_description: "Diplômé de l’École Supérieure de Commerce de Rennes (ESC Rennes), j'ai suivi la formation de développement web au sein du Wagon."
meta_image: "image.jpg"                           # Une image dans votre dossier app/assets/images/
